[package]
name = "lts_node"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
axum = {version = "0.6", features = ["ws", "headers"] }
lts_client = { path = "../lts_client" }
lqos_config = { path = "../../lqos_config" }
serde_json = "1"
pgdb = { path = "../pgdb" }
once_cell = "1"
influxdb2 = "0"
influxdb2-structmap = "0"
num-traits = "0"
futures = "0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
chrono = "0"
miniz_oxide = "0.7.1"
tokio-util = { version = "0.7.8", features = ["io"] }
wasm_pipe_types = { path = "../wasm_pipe_types" }
